# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ruiyuan Kang's peaceful life
repository: RalphKang/Ralph_peaceful_life
email: kang1528530671@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Ruiyuan Kang(康瑞元)'s personal site
twitter_username: RY_Kang666
github_username: RalphKang
minimal_mistakes_skin: sunrise # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true


# Build settings
markdown: kramdown
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ruiyuan(Ralph) Kang"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Learn and share, enjoy peaceful life"
  links:
    - label: "知乎"
      icon: "fab fa-brands fa-zhihu"
      url: "https://www.zhihu.com/people/94de0974588f74ca413425140b018322"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RY_Kang666"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RalphKang"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ruiyaunkang/"

footer:
  links:
    - label: "知乎"
      icon: "fab fa-brands fa-zhihu"
      url: "https://www.zhihu.com/people/94de0974588f74ca413425140b018322"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RY_Kang666"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RalphKang"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ruiyaunkang/"

collections:
  ML:
    output: true
  Aerospace:
    output: true
  Travel:
    output: true



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _ML
  - scope:
      path: ""
      type: ML
    values:
      layout: single
      author_profile: false
      share: true
      comment: true
      sidebar:
        nav: "ML"
  # _Aerospace
  - scope:
      path: ""
      type: Aerospace
    values:
      layout: single
      author_profile: false
      share: true
      comment: true
      sidebar:
        nav: "Aerospace"
  # _Travel
  - scope:
      path: ""
      type: Travel
    values:
      layout: single
      author_profile: false
      share: true
      comment: true
      sidebar:
        nav: "Life"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
